
<?php
/**@var \Inchoo\NewsWithComments\Block\AllNews $block */
?>
<?php $news = $block->getNewsCollection(); ?>

<div class="container">
    <div class="widget block block-static-block">
        <?php foreach ($news as $item): ?>
            <div>
                <h3 class="product name product-item-name">
                    <a href="<?= $block->getSingleNewsUrl($item->getId()); ?>">
                        <?= $block->escapeHtml($item->getTitle()); ?>
                    </a>
                </h3>
                <br>
                <p>
                    <?=$block->escapeHtml($item->getContent());?>
                </p>
                <p class="item product">
                    <?=$block->escapeHtml($item->getAddedAt());?>
                </p>
                <hr>
            </div>
        <?php endforeach;?>
    </div>
</div>
<?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>

<?php else: ?>
    <div class="message info empty"><span><?= __('No any record.'); ?></span></div>
<?php endif ?>