<?php
/**@var \Inchoo\NewsWithComments\Block\SingleNews $block */
?>
<?php $news = $block->getSingleNews(); ?>

<div class="container">
    <div style="text-align:center">
        <h3>
            <?= $block->escapeHtml($news->getTitle()) ?>
        </h3>
        <br>
        <p>
            <?= $block->escapeHtml($news->getContent()) ?>
        </p>
        <p>
            <?= $block->escapeHtml($news->getAddedAt()) ?>
        </p>
        <hr>

        <?php if ($block->isEnabled()): ?>

            <h2><?=__('Comments')?></h2>

            <?php foreach ($news->getComments() as $comment): ?>
                <div>
                   <h4>
                       <?= $block->escapeHtml($comment->getContent()); ?>
                   </h4>
                    <p>
                        By <?= $block->escapeHtml($comment->getAuthor()) . ' at ' . $block->escapeHtml($comment->getAddedAt()); ?>
                    </p>
                </div>


            <?php endforeach; ?>
            <hr>
            <?php if ($block->isLoggedIn()): ?>

                <form action="<?= $block->getSaveAction() ?>" method="post" data-mage-init='{"validation":{}}'>
                    <input name="news_id" type="hidden" value="<?= $news->getId() ?>">
                    <textarea name="comment_content" type="text" data-validate='{"required":true}' style="width: 400px;"></textarea>
                    <br>
                    <input type="submit" value="Comment">
                </form>

            <?php else: ?>

                <h2>You must be <a href="<?= $block->getLoginUrl(); ?>">logged in</a> to comment</h2>

            <?php endif; ?>

        <?php endif; ?>

    </div>
</div>

