<?php
/**@var \Inchoo\NewsWithComments\Block\News $block */
?>
<?php $collection = $block->getNews(); ?>

<?php foreach ($collection as $item): ?>
    <a href="<?= $block->getSingleNewsUrl($item->getId()); ?>">
        <?= $block->escapeHtml($item->getTitle()); ?>
    </a>
<br>
<?=$block->escapeHtml($item->getContent());?>
<br>
<?=$block->escapeHtml($item->getCreatedAt());?>
<hr>

<?php endforeach;?>
